/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kemp_testjni_TestJni */

#ifndef _Included_com_kemp_testjni_TestJni
#define _Included_com_kemp_testjni_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kemp_testjni_TestJni
 * Method:    getJniString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kemp_testjni_TestJni_getJniString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
